# Generated by Django 4.2.16 on 2024-12-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order',
        ),
    ]
