# Generated by Django 4.2.16 on 2024-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_city_profile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_number',
            field=models.CharField(default='1', max_length=10, verbose_name='House number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Bakalynskaya', max_length=150),
            preserve_default=False,
        ),
    ]
