# Generated by Django 4.2.16 on 2024-12-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
    ]
