# Generated by Django 4.2.16 on 2024-12-17 13:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('actived', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_created_b8848b_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='comments_co_created_54dd71_idx'),
        ),
    ]
