# Generated by Django 4.2.16 on 2024-12-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='House number'),
        ),
    ]
