# Generated by Django 4.2.16 on 2024-12-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street',
        ),
    ]
