# Generated by Django 4.2.16 on 2024-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(default='1', max_length=10, verbose_name='House number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='Ural batyra', max_length=150),
            preserve_default=False,
        ),
    ]
